// <auto-generated />
using System;
using Lab_03_CG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab_03_CG.Data.Migrations
{
    [DbContext(typeof(FractalsDbContext))]
    partial class FractalsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("Lab_03_CG.Data.Entities.Fractal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FractalType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fractals");

                    b.HasDiscriminator<string>("FractalType").HasValue("Fractal");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Lab_03_CG.Data.Entities.AlgebraicFractal", b =>
                {
                    b.HasBaseType("Lab_03_CG.Data.Entities.Fractal");

                    b.Property<double>("C_Imaginary")
                        .HasColumnType("REAL");

                    b.Property<double>("C_Real")
                        .HasColumnType("REAL");

                    b.Property<double>("EscapeRadius")
                        .HasColumnType("REAL");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxIterations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Palette")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Z0_Imaginary")
                        .HasColumnType("REAL");

                    b.Property<double>("Z0_Real")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Algebraic");
                });

            modelBuilder.Entity("Lab_03_CG.Data.Entities.GeometricalFractal", b =>
                {
                    b.HasBaseType("Lab_03_CG.Data.Entities.Fractal");

                    b.Property<double>("CenterX")
                        .HasColumnType("REAL");

                    b.Property<double>("CenterY")
                        .HasColumnType("REAL");

                    b.Property<string>("Generator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Initializer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LineColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RotationAngle")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SideLength")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Geometrical");
                });
#pragma warning restore 612, 618
        }
    }
}
