// <auto-generated />
using Lab_01_CG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab_01_CG.Migrations
{
    [DbContext(typeof(SquaresAndCirclesContext))]
    [Migration("20260211193500_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Lab_01_CG.Data.Entities.Circle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CenterX")
                        .HasColumnType("REAL");

                    b.Property<double>("CenterY")
                        .HasColumnType("REAL");

                    b.Property<string>("FillColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutlineColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Radius")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Circles");
                });

            modelBuilder.Entity("Lab_01_CG.Data.Entities.Square", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CenterX")
                        .HasColumnType("REAL");

                    b.Property<double>("CenterY")
                        .HasColumnType("REAL");

                    b.Property<string>("FillColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InnerCircleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OuterCircleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutlineColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SideLength")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("InnerCircleId")
                        .IsUnique();

                    b.HasIndex("OuterCircleId")
                        .IsUnique();

                    b.ToTable("Squares");
                });

            modelBuilder.Entity("Lab_01_CG.Data.Entities.Square", b =>
                {
                    b.HasOne("Lab_01_CG.Data.Entities.Circle", "InnerCircle")
                        .WithOne()
                        .HasForeignKey("Lab_01_CG.Data.Entities.Square", "InnerCircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab_01_CG.Data.Entities.Circle", "OuterCircle")
                        .WithOne()
                        .HasForeignKey("Lab_01_CG.Data.Entities.Square", "OuterCircleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InnerCircle");

                    b.Navigation("OuterCircle");
                });
#pragma warning restore 612, 618
        }
    }
}
